name: adamant_example
services:
    adamant_example:
        image: ghcr.io/lasp/adamant_example:0.1
        build:
            context: .
            dockerfile: Dockerfile
            x-bake:
                platforms:
                    - linux/amd64
                    - linux/arm64
        container_name: adamant_example_container
        volumes:
            - type: bind
              source: ../../adamant
              target: /home/user/adamant
            - type: bind
              source: ../../adamant_example
              target: /home/user/adamant_example
        network_mode: host
        extra_hosts:
            - host.docker.internal:host-gateway
        command: sleep infinity
