#!/bin/bash

# This script sets up the environment for the example project.
echo "Setting up environment..."

# Source the setenv script from the adamant repository:
EXAMPLE_DIR=`readlink -f "${BASH_SOURCE[0]}" | xargs dirname | xargs dirname | xargs dirname`
ADAMANT_DIR=$HOME/adamant
export EXAMPLE_DIR
export ADAMANT_DIR

# Only set the environment once:
if test -n "$EXAMPLE_ENVIRONMENT_SET"
then
  return
fi

# Set the path to our Adamant configuration file for example:
export ADAMANT_CONFIGURATION_YAML=$EXAMPLE_DIR/config/example.configuration.yaml

# Activate the Adamant environment:
. $ADAMANT_DIR/env/activate $EXAMPLE_DIR

# Signify the environment it set up:
export EXAMPLE_ENVIRONMENT_SET="yes"

echo "Done."
